FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y install build-essential python3 libreadline-dev

WORKDIR /berry
COPY . /berry

RUN make

CMD [ "/berry/berry" ]
